
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
  - cron: "0 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: node visualizer/download.js 
      - name: Upload leaderboard
        uses: actions/upload-artifact@v2
        with:
          name: leaderboard
          path: visualizer/leaderboard.json
          
  job_2:
    name: generate html
    needs: job_1
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: leaderboard
          path: ./visualizer
        
      - run: node visualizer/visualizer.js



      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #   echo Add other actions to build,
      #    echo test, and deploy your project.
